# Generated by Django 3.1.1 on 2020-11-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(choices=[('Brighton', 'Brighton'), ('Leeds', 'Leeds'), ('Liverpool', 'Liverpool'), ('Manchester', 'Manchester')], max_length=20)),
                ('size_width_ft', models.IntegerField(blank=True, null=True)),
                ('size_length_ft', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('mirrors', models.BooleanField(default=False)),
                ('music_system', models.BooleanField(default=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('flooring', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('venue_image', models.ImageField(default='default_venue.jpg', upload_to='venue-image/%Y/%m/%d')),
                ('venue_image_1', models.ImageField(blank=True, upload_to='venue-image/%Y/%m/%d')),
                ('venue_image_2', models.ImageField(blank=True, upload_to='venue-image/%Y/%m/%d')),
                ('venue_image_3', models.ImageField(blank=True, upload_to='venue-image/%Y/%m/%d')),
                ('faq', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
