# Generated by Django 3.1.1 on 2020-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='music_system',
            field=models.BooleanField(default=False),
        ),
    ]
