# Generated by Django 3.1.1 on 2020-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact_email',
            field=models.CharField(max_length=250),
        ),
    ]
