# Generated by Django 3.1.1 on 2020-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20201115_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact_email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
