# Generated by Django 3.1.1 on 2020-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
