# Generated by Django 3.1.1 on 2020-10-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatereview',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
