# Generated by Django 3.1.1 on 2020-10-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_candidatereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_style_choice', models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap')], max_length=50)),
                ('location', models.CharField(choices=[('Brighton', 'Brighton'), ('Leeds', 'Leeds'), ('Liverpool', 'Liverpool'), ('Manchester', 'Manchester')], max_length=20)),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.FloatField()),
                ('level', models.CharField(choices=[('Beginners', 'Beginners'), ('General', 'General'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=45)),
                ('dance_class_image', models.ImageField(default='dance_class.jpg', upload_to='dance_class_image/%Y/%m/%d')),
                ('faq', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=10)),
                ('age_group', models.CharField(choices=[('Toddlers', 'Toddlers'), ('Children', 'Children'), ('Teens', 'Teens'), ('Adults', 'Adults')], max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.CharField(blank=True, max_length=90, null=True)),
                ('about_dance_class', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate')),
            ],
        ),
    ]
