# Generated by Django 3.1.1 on 2020-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydanceclass',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weeklydanceclass',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
