# Generated by Django 3.1.1 on 2020-11-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_classes', '0002_auto_20201030_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='dance_style_choice',
            field=models.CharField(choices=[('Select a dance', 'Select a dance'), ('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap')], max_length=50),
        ),
    ]
