# Generated by Django 3.1.1 on 2020-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_classes', '0003_auto_20201103_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='dance_class_image',
            field=models.ImageField(default='dance_class.jpg', upload_to='dance-class-image/%Y/%m/%d'),
        ),
    ]
