# Generated by Django 3.1.1 on 2020-11-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_candidatereview'),
        ('dance_classes', '0004_auto_20201103_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('profile_image', models.ImageField(upload_to='dance-class-pictures/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=250)),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_classes.weeklydanceclass')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate')),
            ],
        ),
    ]
