# Generated by Django 3.1.1 on 2020-11-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_classes', '0005_classimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydanceclass',
            name='dance_class_image_1',
            field=models.ImageField(blank=True, upload_to='dance-class-image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='weeklydanceclass',
            name='dance_class_image_2',
            field=models.ImageField(blank=True, upload_to='dance-class-image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='weeklydanceclass',
            name='dance_class_image_3',
            field=models.ImageField(blank=True, upload_to='dance-class-image/%Y/%m/%d'),
        ),
    ]
