# Generated by Django 3.1.1 on 2020-11-09 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dance_classes', '0006_auto_20201106_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClassReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('rating', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('danceClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_classes.weeklydanceclass')),
            ],
        ),
    ]
