# Generated by Django 3.1.1 on 2020-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_classes', '0008_auto_20201118_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='average_age',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='clothes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='drop_in',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='weeklydanceclass',
            name='experience',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
